std = "lua51"
max_line_length = false

-- Colon methods often intentionally ignore `self` when delegating.
unused_args = false

-- Globals this addon defines or mutates (WoW host + saved variables).
globals = {
   "ColorPickerFrame",
   "NE_STATS_LOCALES",
   "SlashCmdList",
   "StaticPopupDialogs",
   "WoWLogsStatsPrio",
   "ZhuraStatsDB",
   "ZhuraStatsDBBackup",
   "SLASH_ZHURASTATS1",
   "SLASH_ZHURASTATS2",
}

-- WoW API and libraries used across modules (CI runs luacheck on all root *.lua).
read_globals = {
   "C_ClassTalents",
   "C_Timer",
   "C_UnitAuras",
   "CloseDropDownMenus",
   "CombatLogGetCurrentEventInfo",
   "CreateFrame",
   "CR_AVOIDANCE",
   "CR_BLOCK",
   "CR_CRIT",
   "CR_CRIT_MELEE",
   "CR_CRIT_RANGED",
   "CR_CRIT_SPELL",
   "CR_DODGE",
   "CR_HASTE",
   "CR_HASTE_MELEE",
   "CR_HASTE_SPELL",
   "CR_LIFESTEAL",
   "CR_MASTERY",
   "CR_PARRY",
   "CR_SPEED",
   "CR_VERSATILITY",
   "CR_VERSATILITY_DAMAGE_DONE",
   "CR_VERSATILITY_DAMAGE_TAKEN",
   "GameTooltip",
   "geterrorhandler",
   "GetAvoidance",
   "GetAverageItemLevel",
   "GetBlockChance",
   "GetCombatRating",
   "GetCombatRatingBonus",
   "GetCritChance",
   "GetDodgeChance",
   "GetHaste",
   "GetInventoryItemDurability",
   "GetLifesteal",
   "GetLocale",
   "GetMasteryEffect",
   "GetMoney",
   "GetParryChance",
   "GetRangedCritChance",
   "GetRealmName",
   "GetSpecialization",
   "GetSpecializationInfo",
   "GetSpeed",
   "GetSpellCritChance",
   "GetTime",
   "GetUnitSpeed",
   "GetVersatilityBonus",
   "InCombatLockdown",
   "InterfaceOptions_AddCategory",
   "InterfaceOptionsFrame_OpenToCategory",
   "issecretvalue",
   "LibStub",
   "Settings",
   "STANDARD_TEXT_FONT",
   "STATICPOPUP_NUMDIALOGS",
   "StaticPopup_Show",
   "UIDropDownMenu_AddButton",
   "UIDropDownMenu_CreateInfo",
   "UIDropDownMenu_Initialize",
   "UIDropDownMenu_Refresh",
   "UIDropDownMenu_SetSelectedName",
   "UIDropDownMenu_SetSelectedValue",
   "UIDropDownMenu_SetText",
   "UIDropDownMenu_SetWidth",
   "UIParent",
   "UnitClass",
   "UnitGUID",
   "UnitName",
   "UnitStat",
   "strtrim",
   "wipe",
}

files["Locales/*.lua"] = {
   globals = {
      "NE_STATS_LOCALES",
   },
}
