-- Auto-generated by Get-AllStats.ps1
-- Source: archon.gg
-- 2026-05-31T00:02:24Z
-- Fetched: 156 entries (78 stat, 78 hero), skipped: 0

WoWLogsStatsPrio = WoWLogsStatsPrio or {}

WoWLogsStatsPrio["death-knight/blood/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "death-knight", spec = "blood",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 725, order = 2 },
        { stat = "mastery", rating = 620, order = 3 },
        { stat = "haste", rating = 598, order = 4 },
        { stat = "versatility", rating = 291, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/blood/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "death-knight", spec = "blood",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 838, order = 2 },
        { stat = "crit", rating = 820, order = 3 },
        { stat = "mastery", rating = 616, order = 4 },
        { stat = "versatility", rating = 232, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/frost/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "death-knight", spec = "frost",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 950, order = 2 },
        { stat = "crit", rating = 897, order = 3 },
        { stat = "haste", rating = 472, order = 4 },
        { stat = "versatility", rating = 149, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/frost/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "death-knight", spec = "frost",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1113, order = 2 },
        { stat = "crit", rating = 989, order = 3 },
        { stat = "haste", rating = 390, order = 4 },
        { stat = "versatility", rating = 70, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/unholy/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "death-knight", spec = "unholy",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1023, order = 2 },
        { stat = "crit", rating = 958, order = 3 },
        { stat = "haste", rating = 430, order = 4 },
        { stat = "versatility", rating = 127, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/unholy/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "death-knight", spec = "unholy",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1097, order = 2 },
        { stat = "crit", rating = 1000, order = 3 },
        { stat = "haste", rating = 391, order = 4 },
        { stat = "versatility", rating = 68, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/havoc/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "demon-hunter", spec = "havoc",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1070, order = 2 },
        { stat = "mastery", rating = 836, order = 3 },
        { stat = "haste", rating = 392, order = 4 },
        { stat = "versatility", rating = 121, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/havoc/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "demon-hunter", spec = "havoc",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1171, order = 2 },
        { stat = "mastery", rating = 938, order = 3 },
        { stat = "haste", rating = 333, order = 4 },
        { stat = "versatility", rating = 81, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/vengeance/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "demon-hunter", spec = "vengeance",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 991, order = 2 },
        { stat = "crit", rating = 614, order = 3 },
        { stat = "mastery", rating = 397, order = 4 },
        { stat = "versatility", rating = 274, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/vengeance/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "demon-hunter", spec = "vengeance",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1071, order = 2 },
        { stat = "crit", rating = 699, order = 3 },
        { stat = "mastery", rating = 453, order = 4 },
        { stat = "versatility", rating = 264, order = 5 },
    },
}

WoWLogsStatsPrio["druid/balance/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "druid", spec = "balance",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 885, order = 2 },
        { stat = "haste", rating = 780, order = 3 },
        { stat = "crit", rating = 574, order = 4 },
        { stat = "versatility", rating = 167, order = 5 },
    },
}

WoWLogsStatsPrio["druid/balance/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "druid", spec = "balance",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 976, order = 2 },
        { stat = "haste", rating = 747, order = 3 },
        { stat = "crit", rating = 743, order = 4 },
        { stat = "versatility", rating = 128, order = 5 },
    },
}

WoWLogsStatsPrio["druid/feral/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "druid", spec = "feral",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 937, order = 2 },
        { stat = "haste", rating = 727, order = 3 },
        { stat = "crit", rating = 553, order = 4 },
        { stat = "versatility", rating = 180, order = 5 },
    },
}

WoWLogsStatsPrio["druid/feral/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "druid", spec = "feral",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1021, order = 2 },
        { stat = "haste", rating = 813, order = 3 },
        { stat = "crit", rating = 567, order = 4 },
        { stat = "versatility", rating = 162, order = 5 },
    },
}

WoWLogsStatsPrio["druid/guardian/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "druid", spec = "guardian",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1045, order = 2 },
        { stat = "versatility", rating = 475, order = 3 },
        { stat = "mastery", rating = 445, order = 4 },
        { stat = "crit", rating = 368, order = 5 },
    },
}

WoWLogsStatsPrio["druid/guardian/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "druid", spec = "guardian",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1113, order = 2 },
        { stat = "versatility", rating = 478, order = 3 },
        { stat = "mastery", rating = 442, order = 4 },
        { stat = "crit", rating = 399, order = 5 },
    },
}

WoWLogsStatsPrio["druid/restoration/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "druid", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1055, order = 2 },
        { stat = "mastery", rating = 874, order = 3 },
        { stat = "versatility", rating = 227, order = 4 },
        { stat = "crit", rating = 215, order = 5 },
    },
}

WoWLogsStatsPrio["druid/restoration/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "druid", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1196, order = 2 },
        { stat = "mastery", rating = 1038, order = 3 },
        { stat = "versatility", rating = 181, order = 4 },
        { stat = "crit", rating = 158, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/augmentation/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "evoker", spec = "augmentation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1196, order = 2 },
        { stat = "haste", rating = 805, order = 3 },
        { stat = "mastery", rating = 299, order = 4 },
        { stat = "versatility", rating = 126, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/augmentation/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "evoker", spec = "augmentation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1295, order = 2 },
        { stat = "haste", rating = 834, order = 3 },
        { stat = "mastery", rating = 284, order = 4 },
        { stat = "versatility", rating = 89, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/devastation/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "evoker", spec = "devastation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1158, order = 2 },
        { stat = "haste", rating = 752, order = 3 },
        { stat = "mastery", rating = 396, order = 4 },
        { stat = "versatility", rating = 128, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/devastation/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "evoker", spec = "devastation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1252, order = 2 },
        { stat = "haste", rating = 765, order = 3 },
        { stat = "mastery", rating = 414, order = 4 },
        { stat = "versatility", rating = 88, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/preservation/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "evoker", spec = "preservation",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 724, order = 2 },
        { stat = "haste", rating = 684, order = 3 },
        { stat = "crit", rating = 666, order = 4 },
        { stat = "versatility", rating = 159, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/preservation/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "evoker", spec = "preservation",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1184, order = 2 },
        { stat = "crit", rating = 827, order = 3 },
        { stat = "haste", rating = 513, order = 4 },
        { stat = "versatility", rating = 112, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/beast-mastery/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "hunter", spec = "beast-mastery",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 977, order = 2 },
        { stat = "mastery", rating = 839, order = 3 },
        { stat = "haste", rating = 469, order = 4 },
        { stat = "versatility", rating = 126, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/beast-mastery/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "hunter", spec = "beast-mastery",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1038, order = 2 },
        { stat = "mastery", rating = 973, order = 3 },
        { stat = "haste", rating = 499, order = 4 },
        { stat = "versatility", rating = 85, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/marksmanship/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "hunter", spec = "marksmanship",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1189, order = 2 },
        { stat = "mastery", rating = 604, order = 3 },
        { stat = "haste", rating = 445, order = 4 },
        { stat = "versatility", rating = 156, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/marksmanship/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "hunter", spec = "marksmanship",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1319, order = 2 },
        { stat = "mastery", rating = 765, order = 3 },
        { stat = "haste", rating = 418, order = 4 },
        { stat = "versatility", rating = 104, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/survival/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "hunter", spec = "survival",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 997, order = 2 },
        { stat = "crit", rating = 826, order = 3 },
        { stat = "haste", rating = 564, order = 4 },
        { stat = "versatility", rating = 115, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/survival/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "hunter", spec = "survival",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1184, order = 2 },
        { stat = "crit", rating = 825, order = 3 },
        { stat = "haste", rating = 579, order = 4 },
        { stat = "versatility", rating = 87, order = 5 },
    },
}

WoWLogsStatsPrio["mage/arcane/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "mage", spec = "arcane",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 820, order = 2 },
        { stat = "crit", rating = 714, order = 3 },
        { stat = "haste", rating = 651, order = 4 },
        { stat = "versatility", rating = 240, order = 5 },
    },
}

WoWLogsStatsPrio["mage/arcane/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "mage", spec = "arcane",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 861, order = 2 },
        { stat = "crit", rating = 806, order = 3 },
        { stat = "haste", rating = 618, order = 4 },
        { stat = "versatility", rating = 242, order = 5 },
    },
}

WoWLogsStatsPrio["mage/fire/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "mage", spec = "fire",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1050, order = 2 },
        { stat = "mastery", rating = 786, order = 3 },
        { stat = "crit", rating = 234, order = 4 },
        { stat = "versatility", rating = 207, order = 5 },
    },
}

WoWLogsStatsPrio["mage/fire/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "mage", spec = "fire",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1178, order = 2 },
        { stat = "mastery", rating = 944, order = 3 },
        { stat = "versatility", rating = 174, order = 4 },
        { stat = "crit", rating = 168, order = 4 },
    },
}

WoWLogsStatsPrio["mage/frost/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "mage", spec = "frost",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 948, order = 2 },
        { stat = "mastery", rating = 802, order = 3 },
        { stat = "haste", rating = 613, order = 4 },
        { stat = "versatility", rating = 154, order = 5 },
    },
}

WoWLogsStatsPrio["mage/frost/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "mage", spec = "frost",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1063, order = 2 },
        { stat = "mastery", rating = 866, order = 3 },
        { stat = "haste", rating = 568, order = 4 },
        { stat = "versatility", rating = 86, order = 5 },
    },
}

WoWLogsStatsPrio["monk/brewmaster/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "monk", spec = "brewmaster",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1036, order = 2 },
        { stat = "versatility", rating = 676, order = 3 },
        { stat = "mastery", rating = 372, order = 4 },
        { stat = "haste", rating = 336, order = 5 },
    },
}

WoWLogsStatsPrio["monk/brewmaster/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "monk", spec = "brewmaster",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1168, order = 2 },
        { stat = "versatility", rating = 661, order = 3 },
        { stat = "mastery", rating = 416, order = 4 },
        { stat = "haste", rating = 303, order = 5 },
    },
}

WoWLogsStatsPrio["monk/mistweaver/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "monk", spec = "mistweaver",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1063, order = 2 },
        { stat = "crit", rating = 781, order = 3 },
        { stat = "versatility", rating = 291, order = 4 },
        { stat = "mastery", rating = 222, order = 5 },
    },
}

WoWLogsStatsPrio["monk/mistweaver/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "monk", spec = "mistweaver",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1193, order = 2 },
        { stat = "crit", rating = 924, order = 3 },
        { stat = "mastery", rating = 205, order = 4 },
        { stat = "versatility", rating = 194, order = 5 },
    },
}

WoWLogsStatsPrio["monk/windwalker/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "monk", spec = "windwalker",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 855, order = 2 },
        { stat = "crit", rating = 789, order = 3 },
        { stat = "mastery", rating = 524, order = 4 },
        { stat = "versatility", rating = 198, order = 5 },
    },
}

WoWLogsStatsPrio["monk/windwalker/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "monk", spec = "windwalker",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 906, order = 2 },
        { stat = "crit", rating = 833, order = 3 },
        { stat = "mastery", rating = 670, order = 4 },
        { stat = "versatility", rating = 148, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/holy/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "paladin", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 873, order = 2 },
        { stat = "mastery", rating = 775, order = 3 },
        { stat = "crit", rating = 472, order = 4 },
        { stat = "versatility", rating = 213, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/holy/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "paladin", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1083, order = 2 },
        { stat = "haste", rating = 853, order = 3 },
        { stat = "crit", rating = 507, order = 4 },
        { stat = "versatility", rating = 143, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/protection/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "paladin", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 944, order = 2 },
        { stat = "crit", rating = 676, order = 3 },
        { stat = "mastery", rating = 409, order = 4 },
        { stat = "versatility", rating = 248, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/protection/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "paladin", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1037, order = 2 },
        { stat = "crit", rating = 741, order = 3 },
        { stat = "mastery", rating = 447, order = 4 },
        { stat = "versatility", rating = 239, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/retribution/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "paladin", spec = "retribution",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 874, order = 2 },
        { stat = "crit", rating = 797, order = 3 },
        { stat = "haste", rating = 644, order = 4 },
        { stat = "versatility", rating = 120, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/retribution/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "paladin", spec = "retribution",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 971, order = 2 },
        { stat = "crit", rating = 877, order = 3 },
        { stat = "haste", rating = 617, order = 4 },
        { stat = "versatility", rating = 77, order = 5 },
    },
}

WoWLogsStatsPrio["priest/discipline/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "priest", spec = "discipline",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 967, order = 2 },
        { stat = "crit", rating = 772, order = 3 },
        { stat = "mastery", rating = 468, order = 4 },
        { stat = "versatility", rating = 165, order = 5 },
    },
}

WoWLogsStatsPrio["priest/discipline/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "priest", spec = "discipline",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1026, order = 2 },
        { stat = "crit", rating = 883, order = 3 },
        { stat = "mastery", rating = 514, order = 4 },
        { stat = "versatility", rating = 105, order = 5 },
    },
}

WoWLogsStatsPrio["priest/holy/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "priest", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 832, order = 2 },
        { stat = "haste", rating = 716, order = 3 },
        { stat = "mastery", rating = 413, order = 4 },
        { stat = "versatility", rating = 284, order = 5 },
    },
}

WoWLogsStatsPrio["priest/holy/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "priest", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1095, order = 2 },
        { stat = "mastery", rating = 661, order = 3 },
        { stat = "haste", rating = 553, order = 4 },
        { stat = "versatility", rating = 204, order = 5 },
    },
}

WoWLogsStatsPrio["priest/shadow/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "priest", spec = "shadow",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 982, order = 2 },
        { stat = "mastery", rating = 803, order = 3 },
        { stat = "crit", rating = 506, order = 4 },
        { stat = "versatility", rating = 141, order = 5 },
    },
}

WoWLogsStatsPrio["priest/shadow/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "priest", spec = "shadow",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 993, order = 2 },
        { stat = "mastery", rating = 966, order = 3 },
        { stat = "crit", rating = 539, order = 4 },
        { stat = "versatility", rating = 76, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/assassination/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "rogue", spec = "assassination",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1118, order = 2 },
        { stat = "haste", rating = 647, order = 3 },
        { stat = "mastery", rating = 466, order = 4 },
        { stat = "versatility", rating = 137, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/assassination/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "rogue", spec = "assassination",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1211, order = 2 },
        { stat = "haste", rating = 668, order = 3 },
        { stat = "mastery", rating = 509, order = 4 },
        { stat = "versatility", rating = 108, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/outlaw/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "rogue", spec = "outlaw",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1064, order = 2 },
        { stat = "haste", rating = 803, order = 3 },
        { stat = "mastery", rating = 296, order = 4 },
        { stat = "versatility", rating = 199, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/outlaw/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "rogue", spec = "outlaw",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1203, order = 2 },
        { stat = "haste", rating = 873, order = 3 },
        { stat = "mastery", rating = 285, order = 4 },
        { stat = "versatility", rating = 178, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/subtlety/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "rogue", spec = "subtlety",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 980, order = 2 },
        { stat = "crit", rating = 712, order = 3 },
        { stat = "haste", rating = 604, order = 4 },
        { stat = "versatility", rating = 121, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/subtlety/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "rogue", spec = "subtlety",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 990, order = 2 },
        { stat = "crit", rating = 743, order = 3 },
        { stat = "haste", rating = 679, order = 4 },
        { stat = "versatility", rating = 92, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/elemental/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "shaman", spec = "elemental",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1004, order = 2 },
        { stat = "crit", rating = 735, order = 3 },
        { stat = "haste", rating = 514, order = 4 },
        { stat = "versatility", rating = 139, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/elemental/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "shaman", spec = "elemental",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1089, order = 2 },
        { stat = "crit", rating = 871, order = 3 },
        { stat = "haste", rating = 475, order = 4 },
        { stat = "versatility", rating = 94, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/enhancement/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "shaman", spec = "enhancement",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1026, order = 2 },
        { stat = "haste", rating = 851, order = 3 },
        { stat = "crit", rating = 371, order = 4 },
        { stat = "versatility", rating = 136, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/enhancement/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "shaman", spec = "enhancement",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1117, order = 2 },
        { stat = "haste", rating = 959, order = 3 },
        { stat = "crit", rating = 337, order = 4 },
        { stat = "versatility", rating = 83, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/restoration/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "shaman", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1029, order = 2 },
        { stat = "haste", rating = 521, order = 3 },
        { stat = "versatility", rating = 421, order = 4 },
        { stat = "mastery", rating = 333, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/restoration/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "shaman", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1200, order = 2 },
        { stat = "haste", rating = 465, order = 3 },
        { stat = "versatility", rating = 431, order = 4 },
        { stat = "mastery", rating = 344, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/affliction/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "warlock", spec = "affliction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 898, order = 2 },
        { stat = "haste", rating = 850, order = 3 },
        { stat = "mastery", rating = 498, order = 4 },
        { stat = "versatility", rating = 154, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/affliction/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "warlock", spec = "affliction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1057, order = 2 },
        { stat = "haste", rating = 884, order = 3 },
        { stat = "mastery", rating = 531, order = 4 },
        { stat = "versatility", rating = 107, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/demonology/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "warlock", spec = "demonology",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1062, order = 2 },
        { stat = "haste", rating = 801, order = 3 },
        { stat = "mastery", rating = 438, order = 4 },
        { stat = "versatility", rating = 144, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/demonology/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "warlock", spec = "demonology",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1144, order = 2 },
        { stat = "haste", rating = 813, order = 3 },
        { stat = "mastery", rating = 498, order = 4 },
        { stat = "versatility", rating = 94, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/destruction/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "warlock", spec = "destruction",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 845, order = 2 },
        { stat = "crit", rating = 818, order = 3 },
        { stat = "mastery", rating = 513, order = 4 },
        { stat = "versatility", rating = 161, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/destruction/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "warlock", spec = "destruction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1032, order = 2 },
        { stat = "haste", rating = 841, order = 3 },
        { stat = "mastery", rating = 569, order = 4 },
        { stat = "versatility", rating = 90, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/arms/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "warrior", spec = "arms",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 1098, order = 2 },
        { stat = "haste", rating = 915, order = 3 },
        { stat = "mastery", rating = 327, order = 4 },
        { stat = "versatility", rating = 119, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/arms/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "warrior", spec = "arms",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 1143, order = 2 },
        { stat = "haste", rating = 971, order = 3 },
        { stat = "mastery", rating = 343, order = 4 },
        { stat = "versatility", rating = 71, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/fury/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "warrior", spec = "fury",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1041, order = 2 },
        { stat = "mastery", rating = 955, order = 3 },
        { stat = "crit", rating = 508, order = 4 },
        { stat = "versatility", rating = 132, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/fury/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "warrior", spec = "fury",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1079, order = 2 },
        { stat = "mastery", rating = 1075, order = 3 },
        { stat = "crit", rating = 490, order = 4 },
        { stat = "versatility", rating = 87, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/protection/m+"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "m+", class = "warrior", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1037, order = 2 },
        { stat = "crit", rating = 630, order = 3 },
        { stat = "mastery", rating = 377, order = 4 },
        { stat = "versatility", rating = 242, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/protection/raid"] = {
    updated = "2026-05-31T00:02:24Z",
    activity = "raid", class = "warrior", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1127, order = 2 },
        { stat = "crit", rating = 711, order = 3 },
        { stat = "mastery", rating = 459, order = 4 },
        { stat = "versatility", rating = 202, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/blood/m+"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 84.2 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/blood/raid"].heroes = {
        { hero = "san'layn", rank = 1, usage_pct = 0 },
        { hero = "deathbringer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/frost/m+"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 98.5 },
        { hero = "rider-of-the-apocalypse", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/frost/raid"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 99.6 },
        { hero = "rider-of-the-apocalypse", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/unholy/m+"].heroes = {
        { hero = "rider-of-the-apocalypse", rank = 1, usage_pct = 99.8 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/unholy/raid"].heroes = {
        { hero = "rider-of-the-apocalypse", rank = 1, usage_pct = 97.7 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/havoc/m+"].heroes = {
        { hero = "fel-scarred", rank = 1, usage_pct = 0 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/havoc/raid"].heroes = {
        { hero = "fel-scarred", rank = 1, usage_pct = 0 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/vengeance/m+"].heroes = {
        { hero = "annihilator", rank = 1, usage_pct = 98.4 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/vengeance/raid"].heroes = {
        { hero = "annihilator", rank = 1, usage_pct = 99.2 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/balance/m+"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/balance/raid"].heroes = {
        { hero = "keeper-of-the-grove", rank = 1, usage_pct = 91.5 },
        { hero = "elune's-chosen", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/feral/m+"].heroes = {
        { hero = "druid-of-the-claw", rank = 1, usage_pct = 93.4 },
        { hero = "wildstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/feral/raid"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 96.3 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/guardian/m+"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/guardian/raid"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/restoration/m+"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 82.4 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/restoration/raid"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 98.3 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/augmentation/m+"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 99.1 },
        { hero = "chronowarden", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/augmentation/raid"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 53.4 },
        { hero = "chronowarden", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/devastation/m+"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 68 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/devastation/raid"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 83.2 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/preservation/m+"].heroes = {
        { hero = "chronowarden", rank = 1, usage_pct = 89.1 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/preservation/raid"].heroes = {
        { hero = "chronowarden", rank = 1, usage_pct = 81.5 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/beast-mastery/m+"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 65.6 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/beast-mastery/raid"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 98.8 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/marksmanship/m+"].heroes = {
        { hero = "dark-ranger", rank = 1, usage_pct = 87.3 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/marksmanship/raid"].heroes = {
        { hero = "sentinel", rank = 1, usage_pct = 71.5 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/survival/m+"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 98.8 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/survival/raid"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 99.9 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/arcane/m+"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 98.7 },
        { hero = "sunfury", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/arcane/raid"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 99.1 },
        { hero = "sunfury", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/fire/m+"].heroes = {
        { hero = "sunfury", rank = 1, usage_pct = 94.6 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/fire/raid"].heroes = {
        { hero = "sunfury", rank = 1, usage_pct = 96.5 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/frost/m+"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 98.6 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/frost/raid"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 99.9 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/brewmaster/m+"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/brewmaster/raid"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/mistweaver/m+"].heroes = {
        { hero = "conduit-of-the-celestials", rank = 1, usage_pct = 98.1 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/mistweaver/raid"].heroes = {
        { hero = "conduit-of-the-celestials", rank = 1, usage_pct = 96.6 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/windwalker/m+"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "conduit-of-the-celestials", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/windwalker/raid"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "conduit-of-the-celestials", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/holy/m+"].heroes = {
        { hero = "herald-of-the-sun", rank = 1, usage_pct = 90.3 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/holy/raid"].heroes = {
        { hero = "herald-of-the-sun", rank = 1, usage_pct = 99.7 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/protection/m+"].heroes = {
        { hero = "lightsmith", rank = 1, usage_pct = 80.3 },
        { hero = "templar", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/protection/raid"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 87.5 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/retribution/m+"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 99.3 },
        { hero = "herald-of-the-sun", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/retribution/raid"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 99.3 },
        { hero = "herald-of-the-sun", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/discipline/m+"].heroes = {
        { hero = "oracle", rank = 1, usage_pct = 98.2 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/discipline/raid"].heroes = {
        { hero = "oracle", rank = 1, usage_pct = 99.9 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/holy/m+"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 79.2 },
        { hero = "oracle", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/holy/raid"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 98.5 },
        { hero = "oracle", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/shadow/m+"].heroes = {
        { hero = "voidweaver", rank = 1, usage_pct = 58.7 },
        { hero = "archon", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/shadow/raid"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 91.5 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/assassination/m+"].heroes = {
        { hero = "fatebound", rank = 1, usage_pct = 96.9 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/assassination/raid"].heroes = {
        { hero = "fatebound", rank = 1, usage_pct = 99.5 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/outlaw/m+"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 96.3 },
        { hero = "fatebound", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/outlaw/raid"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 95 },
        { hero = "fatebound", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/subtlety/m+"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 99.6 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/subtlety/raid"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 98.9 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/elemental/m+"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 97 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/elemental/raid"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 93.2 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/enhancement/m+"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 71.9 },
        { hero = "totemic", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/enhancement/raid"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 57.2 },
        { hero = "stormbringer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/restoration/m+"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 92.9 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/restoration/raid"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 99.6 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/affliction/m+"].heroes = {
        { hero = "soul-harvester", rank = 1, usage_pct = 95.8 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/affliction/raid"].heroes = {
        { hero = "soul-harvester", rank = 1, usage_pct = 99.6 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/demonology/m+"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 99.3 },
        { hero = "soul-harvester", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/demonology/raid"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 91.6 },
        { hero = "soul-harvester", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/destruction/m+"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 55.8 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/destruction/raid"].heroes = {
        { hero = "hellcaller", rank = 1, usage_pct = 74 },
        { hero = "diabolist", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/arms/m+"].heroes = {
        { hero = "colossus", rank = 1, usage_pct = 56.6 },
        { hero = "slayer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/arms/raid"].heroes = {
        { hero = "slayer", rank = 1, usage_pct = 81.3 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/fury/m+"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 57.4 },
        { hero = "slayer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/fury/raid"].heroes = {
        { hero = "slayer", rank = 1, usage_pct = 60 },
        { hero = "mountain-thane", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/protection/m+"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 96.9 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/protection/raid"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 98.8 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}
