-- Auto-generated by Get-AllStats.ps1
-- Source: archon.gg
-- 2026-06-07T00:04:49Z
-- Fetched: 156 entries (78 stat, 78 hero), skipped: 0

WoWLogsStatsPrio = WoWLogsStatsPrio or {}

WoWLogsStatsPrio["death-knight/blood/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "death-knight", spec = "blood",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 723, order = 2 },
        { stat = "mastery", rating = 625, order = 3 },
        { stat = "haste", rating = 574, order = 4 },
        { stat = "versatility", rating = 292, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/blood/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "death-knight", spec = "blood",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 839, order = 2 },
        { stat = "crit", rating = 826, order = 3 },
        { stat = "mastery", rating = 653, order = 4 },
        { stat = "versatility", rating = 225, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/frost/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "death-knight", spec = "frost",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 949, order = 2 },
        { stat = "crit", rating = 902, order = 3 },
        { stat = "haste", rating = 473, order = 4 },
        { stat = "versatility", rating = 149, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/frost/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "death-knight", spec = "frost",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1132, order = 2 },
        { stat = "crit", rating = 999, order = 3 },
        { stat = "haste", rating = 385, order = 4 },
        { stat = "versatility", rating = 71, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/unholy/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "death-knight", spec = "unholy",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1034, order = 2 },
        { stat = "crit", rating = 974, order = 3 },
        { stat = "haste", rating = 418, order = 4 },
        { stat = "versatility", rating = 125, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/unholy/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "death-knight", spec = "unholy",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1108, order = 2 },
        { stat = "crit", rating = 1014, order = 3 },
        { stat = "haste", rating = 382, order = 4 },
        { stat = "versatility", rating = 68, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/havoc/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "demon-hunter", spec = "havoc",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1068, order = 2 },
        { stat = "mastery", rating = 843, order = 3 },
        { stat = "haste", rating = 390, order = 4 },
        { stat = "versatility", rating = 122, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/havoc/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "demon-hunter", spec = "havoc",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1175, order = 2 },
        { stat = "mastery", rating = 951, order = 3 },
        { stat = "haste", rating = 332, order = 4 },
        { stat = "versatility", rating = 82, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/vengeance/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "demon-hunter", spec = "vengeance",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 993, order = 2 },
        { stat = "crit", rating = 619, order = 3 },
        { stat = "mastery", rating = 400, order = 4 },
        { stat = "versatility", rating = 274, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/vengeance/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "demon-hunter", spec = "vengeance",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1077, order = 2 },
        { stat = "crit", rating = 702, order = 3 },
        { stat = "mastery", rating = 457, order = 4 },
        { stat = "versatility", rating = 261, order = 5 },
    },
}

WoWLogsStatsPrio["druid/balance/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "druid", spec = "balance",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 884, order = 2 },
        { stat = "haste", rating = 783, order = 3 },
        { stat = "crit", rating = 578, order = 4 },
        { stat = "versatility", rating = 169, order = 5 },
    },
}

WoWLogsStatsPrio["druid/balance/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "druid", spec = "balance",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 975, order = 2 },
        { stat = "crit", rating = 784, order = 3 },
        { stat = "haste", rating = 745, order = 4 },
        { stat = "versatility", rating = 130, order = 5 },
    },
}

WoWLogsStatsPrio["druid/feral/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "druid", spec = "feral",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 936, order = 2 },
        { stat = "haste", rating = 733, order = 3 },
        { stat = "crit", rating = 560, order = 4 },
        { stat = "versatility", rating = 181, order = 5 },
    },
}

WoWLogsStatsPrio["druid/feral/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "druid", spec = "feral",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1020, order = 2 },
        { stat = "haste", rating = 819, order = 3 },
        { stat = "crit", rating = 574, order = 4 },
        { stat = "versatility", rating = 169, order = 5 },
    },
}

WoWLogsStatsPrio["druid/guardian/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "druid", spec = "guardian",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1085, order = 2 },
        { stat = "versatility", rating = 515, order = 3 },
        { stat = "mastery", rating = 422, order = 4 },
        { stat = "crit", rating = 363, order = 5 },
    },
}

WoWLogsStatsPrio["druid/guardian/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "druid", spec = "guardian",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1139, order = 2 },
        { stat = "versatility", rating = 516, order = 3 },
        { stat = "mastery", rating = 435, order = 4 },
        { stat = "crit", rating = 397, order = 5 },
    },
}

WoWLogsStatsPrio["druid/restoration/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "druid", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1056, order = 2 },
        { stat = "mastery", rating = 872, order = 3 },
        { stat = "versatility", rating = 230, order = 4 },
        { stat = "crit", rating = 220, order = 5 },
    },
}

WoWLogsStatsPrio["druid/restoration/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "druid", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1206, order = 2 },
        { stat = "mastery", rating = 1051, order = 3 },
        { stat = "versatility", rating = 177, order = 4 },
        { stat = "crit", rating = 158, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/augmentation/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "evoker", spec = "augmentation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1203, order = 2 },
        { stat = "haste", rating = 816, order = 3 },
        { stat = "mastery", rating = 288, order = 4 },
        { stat = "versatility", rating = 121, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/augmentation/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "evoker", spec = "augmentation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1309, order = 2 },
        { stat = "haste", rating = 848, order = 3 },
        { stat = "mastery", rating = 276, order = 4 },
        { stat = "versatility", rating = 88, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/devastation/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "evoker", spec = "devastation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1161, order = 2 },
        { stat = "haste", rating = 750, order = 3 },
        { stat = "mastery", rating = 400, order = 4 },
        { stat = "versatility", rating = 130, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/devastation/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "evoker", spec = "devastation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1254, order = 2 },
        { stat = "haste", rating = 773, order = 3 },
        { stat = "mastery", rating = 413, order = 4 },
        { stat = "versatility", rating = 93, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/preservation/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "evoker", spec = "preservation",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 720, order = 2 },
        { stat = "crit", rating = 703, order = 3 },
        { stat = "haste", rating = 687, order = 4 },
        { stat = "versatility", rating = 163, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/preservation/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "evoker", spec = "preservation",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1191, order = 2 },
        { stat = "crit", rating = 836, order = 3 },
        { stat = "haste", rating = 508, order = 4 },
        { stat = "versatility", rating = 111, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/beast-mastery/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "hunter", spec = "beast-mastery",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1020, order = 2 },
        { stat = "mastery", rating = 841, order = 3 },
        { stat = "haste", rating = 463, order = 4 },
        { stat = "versatility", rating = 127, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/beast-mastery/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "hunter", spec = "beast-mastery",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1044, order = 2 },
        { stat = "mastery", rating = 978, order = 3 },
        { stat = "haste", rating = 481, order = 4 },
        { stat = "versatility", rating = 85, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/marksmanship/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "hunter", spec = "marksmanship",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1190, order = 2 },
        { stat = "mastery", rating = 608, order = 3 },
        { stat = "haste", rating = 445, order = 4 },
        { stat = "versatility", rating = 158, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/marksmanship/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "hunter", spec = "marksmanship",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1324, order = 2 },
        { stat = "mastery", rating = 784, order = 3 },
        { stat = "haste", rating = 416, order = 4 },
        { stat = "versatility", rating = 102, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/survival/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "hunter", spec = "survival",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 997, order = 2 },
        { stat = "crit", rating = 837, order = 3 },
        { stat = "haste", rating = 564, order = 4 },
        { stat = "versatility", rating = 115, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/survival/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "hunter", spec = "survival",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1183, order = 2 },
        { stat = "crit", rating = 834, order = 3 },
        { stat = "haste", rating = 583, order = 4 },
        { stat = "versatility", rating = 86, order = 5 },
    },
}

WoWLogsStatsPrio["mage/arcane/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "mage", spec = "arcane",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 802, order = 2 },
        { stat = "crit", rating = 775, order = 3 },
        { stat = "haste", rating = 639, order = 4 },
        { stat = "versatility", rating = 228, order = 5 },
    },
}

WoWLogsStatsPrio["mage/arcane/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "mage", spec = "arcane",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 867, order = 2 },
        { stat = "mastery", rating = 847, order = 3 },
        { stat = "haste", rating = 614, order = 4 },
        { stat = "versatility", rating = 237, order = 5 },
    },
}

WoWLogsStatsPrio["mage/fire/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "mage", spec = "fire",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1047, order = 2 },
        { stat = "mastery", rating = 824, order = 3 },
        { stat = "crit", rating = 243, order = 4 },
        { stat = "versatility", rating = 205, order = 5 },
    },
}

WoWLogsStatsPrio["mage/fire/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "mage", spec = "fire",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1191, order = 2 },
        { stat = "mastery", rating = 955, order = 3 },
        { stat = "crit", rating = 173, order = 4 },
        { stat = "versatility", rating = 168, order = 4 },
    },
}

WoWLogsStatsPrio["mage/frost/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "mage", spec = "frost",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 950, order = 2 },
        { stat = "mastery", rating = 803, order = 3 },
        { stat = "haste", rating = 618, order = 4 },
        { stat = "versatility", rating = 158, order = 5 },
    },
}

WoWLogsStatsPrio["mage/frost/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "mage", spec = "frost",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1074, order = 2 },
        { stat = "mastery", rating = 873, order = 3 },
        { stat = "haste", rating = 575, order = 4 },
        { stat = "versatility", rating = 85, order = 5 },
    },
}

WoWLogsStatsPrio["monk/brewmaster/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "monk", spec = "brewmaster",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1038, order = 2 },
        { stat = "versatility", rating = 681, order = 3 },
        { stat = "mastery", rating = 372, order = 4 },
        { stat = "haste", rating = 339, order = 5 },
    },
}

WoWLogsStatsPrio["monk/brewmaster/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "monk", spec = "brewmaster",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1175, order = 2 },
        { stat = "versatility", rating = 665, order = 3 },
        { stat = "mastery", rating = 416, order = 4 },
        { stat = "haste", rating = 308, order = 5 },
    },
}

WoWLogsStatsPrio["monk/mistweaver/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "monk", spec = "mistweaver",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1068, order = 2 },
        { stat = "crit", rating = 781, order = 3 },
        { stat = "versatility", rating = 305, order = 4 },
        { stat = "mastery", rating = 217, order = 5 },
    },
}

WoWLogsStatsPrio["monk/mistweaver/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "monk", spec = "mistweaver",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1196, order = 2 },
        { stat = "crit", rating = 942, order = 3 },
        { stat = "versatility", rating = 203, order = 4 },
        { stat = "mastery", rating = 202, order = 4 },
    },
}

WoWLogsStatsPrio["monk/windwalker/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "monk", spec = "windwalker",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 858, order = 2 },
        { stat = "crit", rating = 786, order = 3 },
        { stat = "mastery", rating = 525, order = 4 },
        { stat = "versatility", rating = 195, order = 5 },
    },
}

WoWLogsStatsPrio["monk/windwalker/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "monk", spec = "windwalker",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 911, order = 2 },
        { stat = "crit", rating = 836, order = 3 },
        { stat = "mastery", rating = 680, order = 4 },
        { stat = "versatility", rating = 145, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/holy/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "paladin", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 875, order = 2 },
        { stat = "mastery", rating = 774, order = 3 },
        { stat = "crit", rating = 474, order = 4 },
        { stat = "versatility", rating = 212, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/holy/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "paladin", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1087, order = 2 },
        { stat = "haste", rating = 858, order = 3 },
        { stat = "crit", rating = 511, order = 4 },
        { stat = "versatility", rating = 144, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/protection/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "paladin", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 945, order = 2 },
        { stat = "crit", rating = 679, order = 3 },
        { stat = "mastery", rating = 412, order = 4 },
        { stat = "versatility", rating = 247, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/protection/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "paladin", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1039, order = 2 },
        { stat = "crit", rating = 785, order = 3 },
        { stat = "mastery", rating = 455, order = 4 },
        { stat = "versatility", rating = 231, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/retribution/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "paladin", spec = "retribution",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 880, order = 2 },
        { stat = "crit", rating = 807, order = 3 },
        { stat = "haste", rating = 643, order = 4 },
        { stat = "versatility", rating = 121, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/retribution/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "paladin", spec = "retribution",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 976, order = 2 },
        { stat = "crit", rating = 889, order = 3 },
        { stat = "haste", rating = 617, order = 4 },
        { stat = "versatility", rating = 76, order = 5 },
    },
}

WoWLogsStatsPrio["priest/discipline/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "priest", spec = "discipline",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 964, order = 2 },
        { stat = "crit", rating = 776, order = 3 },
        { stat = "mastery", rating = 473, order = 4 },
        { stat = "versatility", rating = 165, order = 5 },
    },
}

WoWLogsStatsPrio["priest/discipline/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "priest", spec = "discipline",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1018, order = 2 },
        { stat = "crit", rating = 893, order = 3 },
        { stat = "mastery", rating = 522, order = 4 },
        { stat = "versatility", rating = 102, order = 5 },
    },
}

WoWLogsStatsPrio["priest/holy/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "priest", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 833, order = 2 },
        { stat = "haste", rating = 721, order = 3 },
        { stat = "mastery", rating = 412, order = 4 },
        { stat = "versatility", rating = 287, order = 5 },
    },
}

WoWLogsStatsPrio["priest/holy/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "priest", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1104, order = 2 },
        { stat = "mastery", rating = 665, order = 3 },
        { stat = "haste", rating = 552, order = 4 },
        { stat = "versatility", rating = 201, order = 5 },
    },
}

WoWLogsStatsPrio["priest/shadow/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "priest", spec = "shadow",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 987, order = 2 },
        { stat = "mastery", rating = 797, order = 3 },
        { stat = "crit", rating = 517, order = 4 },
        { stat = "versatility", rating = 140, order = 5 },
    },
}

WoWLogsStatsPrio["priest/shadow/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "priest", spec = "shadow",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1005, order = 2 },
        { stat = "mastery", rating = 959, order = 3 },
        { stat = "crit", rating = 564, order = 4 },
        { stat = "versatility", rating = 75, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/assassination/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "rogue", spec = "assassination",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1123, order = 2 },
        { stat = "haste", rating = 647, order = 3 },
        { stat = "mastery", rating = 467, order = 4 },
        { stat = "versatility", rating = 139, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/assassination/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "rogue", spec = "assassination",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1221, order = 2 },
        { stat = "haste", rating = 676, order = 3 },
        { stat = "mastery", rating = 506, order = 4 },
        { stat = "versatility", rating = 107, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/outlaw/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "rogue", spec = "outlaw",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1098, order = 2 },
        { stat = "haste", rating = 818, order = 3 },
        { stat = "mastery", rating = 295, order = 4 },
        { stat = "versatility", rating = 198, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/outlaw/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "rogue", spec = "outlaw",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1238, order = 2 },
        { stat = "haste", rating = 877, order = 3 },
        { stat = "mastery", rating = 282, order = 4 },
        { stat = "versatility", rating = 179, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/subtlety/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "rogue", spec = "subtlety",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 987, order = 2 },
        { stat = "crit", rating = 709, order = 3 },
        { stat = "haste", rating = 607, order = 4 },
        { stat = "versatility", rating = 122, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/subtlety/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "rogue", spec = "subtlety",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1004, order = 2 },
        { stat = "crit", rating = 738, order = 3 },
        { stat = "haste", rating = 691, order = 4 },
        { stat = "versatility", rating = 91, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/elemental/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "shaman", spec = "elemental",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1004, order = 2 },
        { stat = "crit", rating = 767, order = 3 },
        { stat = "haste", rating = 509, order = 4 },
        { stat = "versatility", rating = 138, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/elemental/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "shaman", spec = "elemental",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1091, order = 2 },
        { stat = "crit", rating = 889, order = 3 },
        { stat = "haste", rating = 470, order = 4 },
        { stat = "versatility", rating = 96, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/enhancement/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "shaman", spec = "enhancement",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 990, order = 2 },
        { stat = "haste", rating = 856, order = 3 },
        { stat = "crit", rating = 385, order = 4 },
        { stat = "versatility", rating = 135, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/enhancement/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "shaman", spec = "enhancement",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1101, order = 2 },
        { stat = "haste", rating = 964, order = 3 },
        { stat = "crit", rating = 369, order = 4 },
        { stat = "versatility", rating = 81, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/restoration/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "shaman", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1030, order = 2 },
        { stat = "haste", rating = 525, order = 3 },
        { stat = "versatility", rating = 427, order = 4 },
        { stat = "mastery", rating = 332, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/restoration/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "shaman", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1207, order = 2 },
        { stat = "haste", rating = 468, order = 3 },
        { stat = "versatility", rating = 438, order = 4 },
        { stat = "mastery", rating = 347, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/affliction/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "warlock", spec = "affliction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 900, order = 2 },
        { stat = "haste", rating = 853, order = 3 },
        { stat = "mastery", rating = 503, order = 4 },
        { stat = "versatility", rating = 157, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/affliction/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "warlock", spec = "affliction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1064, order = 2 },
        { stat = "haste", rating = 888, order = 3 },
        { stat = "mastery", rating = 527, order = 4 },
        { stat = "versatility", rating = 105, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/demonology/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "warlock", spec = "demonology",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1060, order = 2 },
        { stat = "haste", rating = 804, order = 3 },
        { stat = "mastery", rating = 457, order = 4 },
        { stat = "versatility", rating = 145, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/demonology/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "warlock", spec = "demonology",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1149, order = 2 },
        { stat = "haste", rating = 817, order = 3 },
        { stat = "mastery", rating = 510, order = 4 },
        { stat = "versatility", rating = 91, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/destruction/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "warlock", spec = "destruction",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 860, order = 2 },
        { stat = "crit", rating = 825, order = 3 },
        { stat = "mastery", rating = 515, order = 4 },
        { stat = "versatility", rating = 163, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/destruction/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "warlock", spec = "destruction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1041, order = 2 },
        { stat = "haste", rating = 843, order = 3 },
        { stat = "mastery", rating = 572, order = 4 },
        { stat = "versatility", rating = 89, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/arms/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "warrior", spec = "arms",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 1109, order = 2 },
        { stat = "haste", rating = 921, order = 3 },
        { stat = "mastery", rating = 328, order = 4 },
        { stat = "versatility", rating = 117, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/arms/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "warrior", spec = "arms",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 1153, order = 2 },
        { stat = "haste", rating = 979, order = 3 },
        { stat = "mastery", rating = 348, order = 4 },
        { stat = "versatility", rating = 70, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/fury/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "warrior", spec = "fury",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1049, order = 2 },
        { stat = "mastery", rating = 954, order = 3 },
        { stat = "crit", rating = 513, order = 4 },
        { stat = "versatility", rating = 133, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/fury/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "warrior", spec = "fury",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1089, order = 2 },
        { stat = "mastery", rating = 1081, order = 3 },
        { stat = "crit", rating = 495, order = 4 },
        { stat = "versatility", rating = 87, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/protection/m+"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "m+", class = "warrior", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1039, order = 2 },
        { stat = "crit", rating = 631, order = 3 },
        { stat = "mastery", rating = 378, order = 4 },
        { stat = "versatility", rating = 244, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/protection/raid"] = {
    updated = "2026-06-07T00:04:49Z",
    activity = "raid", class = "warrior", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1131, order = 2 },
        { stat = "crit", rating = 719, order = 3 },
        { stat = "mastery", rating = 464, order = 4 },
        { stat = "versatility", rating = 197, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/blood/m+"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 85 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/blood/raid"].heroes = {
        { hero = "san'layn", rank = 1, usage_pct = 0 },
        { hero = "deathbringer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/frost/m+"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 98.5 },
        { hero = "rider-of-the-apocalypse", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/frost/raid"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 99.7 },
        { hero = "rider-of-the-apocalypse", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/unholy/m+"].heroes = {
        { hero = "rider-of-the-apocalypse", rank = 1, usage_pct = 99.8 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/unholy/raid"].heroes = {
        { hero = "rider-of-the-apocalypse", rank = 1, usage_pct = 97.6 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/havoc/m+"].heroes = {
        { hero = "fel-scarred", rank = 1, usage_pct = 0 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/havoc/raid"].heroes = {
        { hero = "fel-scarred", rank = 1, usage_pct = 0 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/vengeance/m+"].heroes = {
        { hero = "annihilator", rank = 1, usage_pct = 97.1 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/vengeance/raid"].heroes = {
        { hero = "annihilator", rank = 1, usage_pct = 98.1 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/balance/m+"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/balance/raid"].heroes = {
        { hero = "keeper-of-the-grove", rank = 1, usage_pct = 90.4 },
        { hero = "elune's-chosen", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/feral/m+"].heroes = {
        { hero = "druid-of-the-claw", rank = 1, usage_pct = 93.5 },
        { hero = "wildstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/feral/raid"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 95.2 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/guardian/m+"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/guardian/raid"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/restoration/m+"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 82.7 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/restoration/raid"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 98.5 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/augmentation/m+"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 99.1 },
        { hero = "chronowarden", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/augmentation/raid"].heroes = {
        { hero = "chronowarden", rank = 1, usage_pct = 50.7 },
        { hero = "scalecommander", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/devastation/m+"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 67 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/devastation/raid"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 81.4 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/preservation/m+"].heroes = {
        { hero = "chronowarden", rank = 1, usage_pct = 87.3 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/preservation/raid"].heroes = {
        { hero = "chronowarden", rank = 1, usage_pct = 72.6 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/beast-mastery/m+"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 71.4 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/beast-mastery/raid"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 99 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/marksmanship/m+"].heroes = {
        { hero = "dark-ranger", rank = 1, usage_pct = 88.1 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/marksmanship/raid"].heroes = {
        { hero = "sentinel", rank = 1, usage_pct = 72 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/survival/m+"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 98.8 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/survival/raid"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 99.9 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/arcane/m+"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 98.5 },
        { hero = "sunfury", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/arcane/raid"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 98.7 },
        { hero = "sunfury", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/fire/m+"].heroes = {
        { hero = "sunfury", rank = 1, usage_pct = 93.8 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/fire/raid"].heroes = {
        { hero = "sunfury", rank = 1, usage_pct = 95.9 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/frost/m+"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 97.6 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/frost/raid"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 99.9 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/brewmaster/m+"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/brewmaster/raid"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/mistweaver/m+"].heroes = {
        { hero = "conduit-of-the-celestials", rank = 1, usage_pct = 98.4 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/mistweaver/raid"].heroes = {
        { hero = "conduit-of-the-celestials", rank = 1, usage_pct = 96.8 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/windwalker/m+"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "conduit-of-the-celestials", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/windwalker/raid"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "conduit-of-the-celestials", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/holy/m+"].heroes = {
        { hero = "herald-of-the-sun", rank = 1, usage_pct = 91.7 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/holy/raid"].heroes = {
        { hero = "herald-of-the-sun", rank = 1, usage_pct = 99.7 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/protection/m+"].heroes = {
        { hero = "lightsmith", rank = 1, usage_pct = 80.1 },
        { hero = "templar", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/protection/raid"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 87.2 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/retribution/m+"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 98.4 },
        { hero = "herald-of-the-sun", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/retribution/raid"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 96.5 },
        { hero = "herald-of-the-sun", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/discipline/m+"].heroes = {
        { hero = "oracle", rank = 1, usage_pct = 98.3 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/discipline/raid"].heroes = {
        { hero = "oracle", rank = 1, usage_pct = 99.9 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/holy/m+"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 77.7 },
        { hero = "oracle", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/holy/raid"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 98.4 },
        { hero = "oracle", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/shadow/m+"].heroes = {
        { hero = "voidweaver", rank = 1, usage_pct = 63.4 },
        { hero = "archon", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/shadow/raid"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 90.4 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/assassination/m+"].heroes = {
        { hero = "fatebound", rank = 1, usage_pct = 94.1 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/assassination/raid"].heroes = {
        { hero = "fatebound", rank = 1, usage_pct = 99.1 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/outlaw/m+"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 96.9 },
        { hero = "fatebound", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/outlaw/raid"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 95.3 },
        { hero = "fatebound", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/subtlety/m+"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 99.4 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/subtlety/raid"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 97.6 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/elemental/m+"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 91.4 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/elemental/raid"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 85.5 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/enhancement/m+"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 77.5 },
        { hero = "totemic", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/enhancement/raid"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 50.1 },
        { hero = "totemic", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/restoration/m+"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 93.9 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/restoration/raid"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 99.6 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/affliction/m+"].heroes = {
        { hero = "soul-harvester", rank = 1, usage_pct = 96.2 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/affliction/raid"].heroes = {
        { hero = "soul-harvester", rank = 1, usage_pct = 99.8 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/demonology/m+"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 99.2 },
        { hero = "soul-harvester", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/demonology/raid"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 93.2 },
        { hero = "soul-harvester", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/destruction/m+"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 55.9 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/destruction/raid"].heroes = {
        { hero = "hellcaller", rank = 1, usage_pct = 72.2 },
        { hero = "diabolist", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/arms/m+"].heroes = {
        { hero = "colossus", rank = 1, usage_pct = 69.9 },
        { hero = "slayer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/arms/raid"].heroes = {
        { hero = "slayer", rank = 1, usage_pct = 80 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/fury/m+"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 61.4 },
        { hero = "slayer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/fury/raid"].heroes = {
        { hero = "slayer", rank = 1, usage_pct = 57 },
        { hero = "mountain-thane", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/protection/m+"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 97.1 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/protection/raid"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 98.8 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}
