-- Auto-generated by Get-AllStats.ps1
-- Source: archon.gg
-- 2026-05-01T18:52:26Z
-- Fetched: 156 entries (78 stat, 78 hero), skipped: 0

WoWLogsStatsPrio = WoWLogsStatsPrio or {}

WoWLogsStatsPrio["death-knight/blood/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "death-knight", spec = "blood",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 677, order = 2 },
        { stat = "haste", rating = 571, order = 3 },
        { stat = "mastery", rating = 567, order = 4 },
        { stat = "versatility", rating = 290, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/blood/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "death-knight", spec = "blood",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 793, order = 2 },
        { stat = "crit", rating = 760, order = 3 },
        { stat = "mastery", rating = 551, order = 4 },
        { stat = "versatility", rating = 251, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/frost/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "death-knight", spec = "frost",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 835, order = 2 },
        { stat = "mastery", rating = 840, order = 2 },
        { stat = "haste", rating = 483, order = 3 },
        { stat = "versatility", rating = 145, order = 4 },
    },
}

WoWLogsStatsPrio["death-knight/frost/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "death-knight", spec = "frost",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1020, order = 2 },
        { stat = "crit", rating = 922, order = 3 },
        { stat = "haste", rating = 436, order = 4 },
        { stat = "versatility", rating = 86, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/unholy/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "death-knight", spec = "unholy",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 965, order = 2 },
        { stat = "crit", rating = 851, order = 3 },
        { stat = "haste", rating = 466, order = 4 },
        { stat = "versatility", rating = 129, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/unholy/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "death-knight", spec = "unholy",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1045, order = 2 },
        { stat = "crit", rating = 914, order = 3 },
        { stat = "haste", rating = 432, order = 4 },
        { stat = "versatility", rating = 72, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/havoc/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "demon-hunter", spec = "havoc",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1036, order = 2 },
        { stat = "mastery", rating = 741, order = 3 },
        { stat = "haste", rating = 393, order = 4 },
        { stat = "versatility", rating = 127, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/havoc/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "demon-hunter", spec = "havoc",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1118, order = 2 },
        { stat = "mastery", rating = 873, order = 3 },
        { stat = "haste", rating = 329, order = 4 },
        { stat = "versatility", rating = 82, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/vengeance/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "demon-hunter", spec = "vengeance",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 927, order = 2 },
        { stat = "crit", rating = 570, order = 3 },
        { stat = "mastery", rating = 388, order = 4 },
        { stat = "versatility", rating = 285, order = 5 },
    },
}

WoWLogsStatsPrio["demon-hunter/vengeance/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "demon-hunter", spec = "vengeance",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1033, order = 2 },
        { stat = "crit", rating = 674, order = 3 },
        { stat = "mastery", rating = 372, order = 4 },
        { stat = "versatility", rating = 277, order = 5 },
    },
}

WoWLogsStatsPrio["druid/balance/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "druid", spec = "balance",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 926, order = 2 },
        { stat = "haste", rating = 727, order = 3 },
        { stat = "crit", rating = 482, order = 4 },
        { stat = "versatility", rating = 158, order = 5 },
    },
}

WoWLogsStatsPrio["druid/balance/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "druid", spec = "balance",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1015, order = 2 },
        { stat = "haste", rating = 705, order = 3 },
        { stat = "crit", rating = 636, order = 4 },
        { stat = "versatility", rating = 115, order = 5 },
    },
}

WoWLogsStatsPrio["druid/feral/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "druid", spec = "feral",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 932, order = 2 },
        { stat = "haste", rating = 667, order = 3 },
        { stat = "crit", rating = 521, order = 4 },
        { stat = "versatility", rating = 162, order = 5 },
    },
}

WoWLogsStatsPrio["druid/feral/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "druid", spec = "feral",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1025, order = 2 },
        { stat = "haste", rating = 759, order = 3 },
        { stat = "crit", rating = 550, order = 4 },
        { stat = "versatility", rating = 115, order = 5 },
    },
}

WoWLogsStatsPrio["druid/guardian/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "druid", spec = "guardian",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 885, order = 2 },
        { stat = "mastery", rating = 490, order = 3 },
        { stat = "versatility", rating = 410, order = 4 },
        { stat = "crit", rating = 372, order = 5 },
    },
}

WoWLogsStatsPrio["druid/guardian/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "druid", spec = "guardian",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 1027, order = 2 },
        { stat = "mastery", rating = 503, order = 3 },
        { stat = "versatility", rating = 416, order = 4 },
        { stat = "crit", rating = 423, order = 4 },
    },
}

WoWLogsStatsPrio["druid/restoration/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "druid", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1010, order = 2 },
        { stat = "mastery", rating = 824, order = 3 },
        { stat = "versatility", rating = 224, order = 4 },
        { stat = "crit", rating = 213, order = 5 },
    },
}

WoWLogsStatsPrio["druid/restoration/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "druid", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1151, order = 2 },
        { stat = "mastery", rating = 964, order = 3 },
        { stat = "versatility", rating = 183, order = 4 },
        { stat = "crit", rating = 149, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/augmentation/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "evoker", spec = "augmentation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1109, order = 2 },
        { stat = "haste", rating = 717, order = 3 },
        { stat = "mastery", rating = 327, order = 4 },
        { stat = "versatility", rating = 144, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/augmentation/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "evoker", spec = "augmentation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1252, order = 2 },
        { stat = "haste", rating = 764, order = 3 },
        { stat = "mastery", rating = 293, order = 4 },
        { stat = "versatility", rating = 93, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/devastation/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "evoker", spec = "devastation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1087, order = 2 },
        { stat = "haste", rating = 682, order = 3 },
        { stat = "mastery", rating = 412, order = 4 },
        { stat = "versatility", rating = 133, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/devastation/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "evoker", spec = "devastation",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1208, order = 2 },
        { stat = "haste", rating = 686, order = 3 },
        { stat = "mastery", rating = 426, order = 4 },
        { stat = "versatility", rating = 95, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/preservation/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "evoker", spec = "preservation",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 722, order = 2 },
        { stat = "haste", rating = 638, order = 3 },
        { stat = "crit", rating = 605, order = 4 },
        { stat = "versatility", rating = 164, order = 5 },
    },
}

WoWLogsStatsPrio["evoker/preservation/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "evoker", spec = "preservation",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1128, order = 2 },
        { stat = "crit", rating = 706, order = 3 },
        { stat = "haste", rating = 526, order = 4 },
        { stat = "versatility", rating = 119, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/beast-mastery/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "hunter", spec = "beast-mastery",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 887, order = 2 },
        { stat = "mastery", rating = 784, order = 3 },
        { stat = "haste", rating = 461, order = 4 },
        { stat = "versatility", rating = 127, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/beast-mastery/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "hunter", spec = "beast-mastery",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 947, order = 2 },
        { stat = "mastery", rating = 930, order = 3 },
        { stat = "haste", rating = 489, order = 4 },
        { stat = "versatility", rating = 90, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/marksmanship/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "hunter", spec = "marksmanship",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1142, order = 2 },
        { stat = "mastery", rating = 565, order = 3 },
        { stat = "haste", rating = 423, order = 4 },
        { stat = "versatility", rating = 144, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/marksmanship/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "hunter", spec = "marksmanship",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1270, order = 2 },
        { stat = "mastery", rating = 689, order = 3 },
        { stat = "haste", rating = 402, order = 4 },
        { stat = "versatility", rating = 115, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/survival/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "hunter", spec = "survival",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 980, order = 2 },
        { stat = "crit", rating = 773, order = 3 },
        { stat = "haste", rating = 544, order = 4 },
        { stat = "versatility", rating = 120, order = 5 },
    },
}

WoWLogsStatsPrio["hunter/survival/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "hunter", spec = "survival",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1166, order = 2 },
        { stat = "crit", rating = 779, order = 3 },
        { stat = "haste", rating = 556, order = 4 },
        { stat = "versatility", rating = 88, order = 5 },
    },
}

WoWLogsStatsPrio["mage/arcane/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "mage", spec = "arcane",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 769, order = 2 },
        { stat = "haste", rating = 628, order = 3 },
        { stat = "crit", rating = 623, order = 4 },
        { stat = "versatility", rating = 229, order = 5 },
    },
}

WoWLogsStatsPrio["mage/arcane/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "mage", spec = "arcane",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 839, order = 2 },
        { stat = "crit", rating = 663, order = 3 },
        { stat = "haste", rating = 643, order = 4 },
        { stat = "versatility", rating = 241, order = 5 },
    },
}

WoWLogsStatsPrio["mage/fire/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "mage", spec = "fire",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1001, order = 2 },
        { stat = "mastery", rating = 763, order = 3 },
        { stat = "crit", rating = 240, order = 4 },
        { stat = "versatility", rating = 197, order = 5 },
    },
}

WoWLogsStatsPrio["mage/fire/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "mage", spec = "fire",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1154, order = 2 },
        { stat = "mastery", rating = 876, order = 3 },
        { stat = "crit", rating = 154, order = 4 },
        { stat = "versatility", rating = 157, order = 4 },
    },
}

WoWLogsStatsPrio["mage/frost/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "mage", spec = "frost",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 848, order = 2 },
        { stat = "mastery", rating = 779, order = 3 },
        { stat = "haste", rating = 599, order = 4 },
        { stat = "versatility", rating = 145, order = 5 },
    },
}

WoWLogsStatsPrio["mage/frost/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "mage", spec = "frost",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1003, order = 2 },
        { stat = "mastery", rating = 826, order = 3 },
        { stat = "haste", rating = 560, order = 4 },
        { stat = "versatility", rating = 96, order = 5 },
    },
}

WoWLogsStatsPrio["monk/brewmaster/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "monk", spec = "brewmaster",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 992, order = 2 },
        { stat = "versatility", rating = 626, order = 3 },
        { stat = "mastery", rating = 359, order = 4 },
        { stat = "haste", rating = 340, order = 5 },
    },
}

WoWLogsStatsPrio["monk/brewmaster/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "monk", spec = "brewmaster",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1125, order = 2 },
        { stat = "versatility", rating = 640, order = 3 },
        { stat = "mastery", rating = 397, order = 4 },
        { stat = "haste", rating = 287, order = 5 },
    },
}

WoWLogsStatsPrio["monk/mistweaver/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "monk", spec = "mistweaver",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1035, order = 2 },
        { stat = "crit", rating = 723, order = 3 },
        { stat = "versatility", rating = 257, order = 4 },
        { stat = "mastery", rating = 231, order = 5 },
    },
}

WoWLogsStatsPrio["monk/mistweaver/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "monk", spec = "mistweaver",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1180, order = 2 },
        { stat = "crit", rating = 874, order = 3 },
        { stat = "versatility", rating = 175, order = 4 },
        { stat = "mastery", rating = 177, order = 4 },
    },
}

WoWLogsStatsPrio["monk/windwalker/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "monk", spec = "windwalker",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 863, order = 2 },
        { stat = "crit", rating = 743, order = 3 },
        { stat = "mastery", rating = 509, order = 4 },
        { stat = "versatility", rating = 199, order = 5 },
    },
}

WoWLogsStatsPrio["monk/windwalker/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "monk", spec = "windwalker",
    primary = "agility",
    secondary = {
        { stat = "haste", rating = 922, order = 2 },
        { stat = "crit", rating = 798, order = 3 },
        { stat = "mastery", rating = 632, order = 4 },
        { stat = "versatility", rating = 144, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/holy/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "paladin", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 824, order = 2 },
        { stat = "mastery", rating = 716, order = 3 },
        { stat = "crit", rating = 462, order = 4 },
        { stat = "versatility", rating = 212, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/holy/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "paladin", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1026, order = 2 },
        { stat = "haste", rating = 813, order = 3 },
        { stat = "crit", rating = 436, order = 4 },
        { stat = "versatility", rating = 146, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/protection/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "paladin", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 919, order = 2 },
        { stat = "crit", rating = 573, order = 3 },
        { stat = "mastery", rating = 398, order = 4 },
        { stat = "versatility", rating = 265, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/protection/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "paladin", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1031, order = 2 },
        { stat = "crit", rating = 638, order = 3 },
        { stat = "mastery", rating = 395, order = 4 },
        { stat = "versatility", rating = 270, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/retribution/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "paladin", spec = "retribution",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 797, order = 2 },
        { stat = "crit", rating = 700, order = 3 },
        { stat = "haste", rating = 651, order = 4 },
        { stat = "versatility", rating = 130, order = 5 },
    },
}

WoWLogsStatsPrio["paladin/retribution/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "paladin", spec = "retribution",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 924, order = 2 },
        { stat = "crit", rating = 791, order = 3 },
        { stat = "haste", rating = 632, order = 4 },
        { stat = "versatility", rating = 77, order = 5 },
    },
}

WoWLogsStatsPrio["priest/discipline/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "priest", spec = "discipline",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 930, order = 2 },
        { stat = "crit", rating = 674, order = 3 },
        { stat = "mastery", rating = 443, order = 4 },
        { stat = "versatility", rating = 179, order = 5 },
    },
}

WoWLogsStatsPrio["priest/discipline/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "priest", spec = "discipline",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 1082, order = 2 },
        { stat = "crit", rating = 779, order = 3 },
        { stat = "mastery", rating = 447, order = 4 },
        { stat = "versatility", rating = 124, order = 5 },
    },
}

WoWLogsStatsPrio["priest/holy/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "priest", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 775, order = 2 },
        { stat = "haste", rating = 676, order = 3 },
        { stat = "mastery", rating = 406, order = 4 },
        { stat = "versatility", rating = 280, order = 5 },
    },
}

WoWLogsStatsPrio["priest/holy/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "priest", spec = "holy",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1039, order = 2 },
        { stat = "mastery", rating = 565, order = 3 },
        { stat = "haste", rating = 540, order = 4 },
        { stat = "versatility", rating = 223, order = 5 },
    },
}

WoWLogsStatsPrio["priest/shadow/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "priest", spec = "shadow",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 936, order = 2 },
        { stat = "mastery", rating = 796, order = 3 },
        { stat = "crit", rating = 434, order = 4 },
        { stat = "versatility", rating = 143, order = 5 },
    },
}

WoWLogsStatsPrio["priest/shadow/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "priest", spec = "shadow",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 973, order = 2 },
        { stat = "haste", rating = 957, order = 3 },
        { stat = "crit", rating = 471, order = 4 },
        { stat = "versatility", rating = 86, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/assassination/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "rogue", spec = "assassination",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1040, order = 2 },
        { stat = "haste", rating = 603, order = 3 },
        { stat = "mastery", rating = 502, order = 4 },
        { stat = "versatility", rating = 139, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/assassination/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "rogue", spec = "assassination",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1132, order = 2 },
        { stat = "haste", rating = 640, order = 3 },
        { stat = "mastery", rating = 524, order = 4 },
        { stat = "versatility", rating = 108, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/outlaw/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "rogue", spec = "outlaw",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 992, order = 2 },
        { stat = "haste", rating = 771, order = 3 },
        { stat = "mastery", rating = 305, order = 4 },
        { stat = "versatility", rating = 207, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/outlaw/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "rogue", spec = "outlaw",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 1122, order = 2 },
        { stat = "haste", rating = 832, order = 3 },
        { stat = "mastery", rating = 288, order = 4 },
        { stat = "versatility", rating = 177, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/subtlety/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "rogue", spec = "subtlety",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 931, order = 2 },
        { stat = "crit", rating = 633, order = 3 },
        { stat = "haste", rating = 561, order = 4 },
        { stat = "versatility", rating = 136, order = 5 },
    },
}

WoWLogsStatsPrio["rogue/subtlety/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "rogue", spec = "subtlety",
    primary = "agility",
    secondary = {
        { stat = "crit", rating = 828, order = 2 },
        { stat = "mastery", rating = 810, order = 3 },
        { stat = "haste", rating = 667, order = 4 },
        { stat = "versatility", rating = 96, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/elemental/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "shaman", spec = "elemental",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 945, order = 2 },
        { stat = "crit", rating = 665, order = 3 },
        { stat = "haste", rating = 541, order = 4 },
        { stat = "versatility", rating = 138, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/elemental/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "shaman", spec = "elemental",
    primary = "intellect",
    secondary = {
        { stat = "mastery", rating = 1068, order = 2 },
        { stat = "crit", rating = 771, order = 3 },
        { stat = "haste", rating = 499, order = 4 },
        { stat = "versatility", rating = 88, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/enhancement/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "shaman", spec = "enhancement",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1043, order = 2 },
        { stat = "haste", rating = 795, order = 3 },
        { stat = "crit", rating = 310, order = 4 },
        { stat = "versatility", rating = 139, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/enhancement/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "shaman", spec = "enhancement",
    primary = "agility",
    secondary = {
        { stat = "mastery", rating = 1196, order = 2 },
        { stat = "haste", rating = 915, order = 3 },
        { stat = "crit", rating = 264, order = 4 },
        { stat = "versatility", rating = 89, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/restoration/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "shaman", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 937, order = 2 },
        { stat = "haste", rating = 504, order = 3 },
        { stat = "mastery", rating = 345, order = 4 },
        { stat = "versatility", rating = 335, order = 5 },
    },
}

WoWLogsStatsPrio["shaman/restoration/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "shaman", spec = "restoration",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1154, order = 2 },
        { stat = "haste", rating = 438, order = 3 },
        { stat = "versatility", rating = 375, order = 4 },
        { stat = "mastery", rating = 341, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/affliction/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "warlock", spec = "affliction",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 834, order = 2 },
        { stat = "crit", rating = 783, order = 3 },
        { stat = "mastery", rating = 460, order = 4 },
        { stat = "versatility", rating = 154, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/affliction/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "warlock", spec = "affliction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 929, order = 2 },
        { stat = "haste", rating = 879, order = 3 },
        { stat = "mastery", rating = 458, order = 4 },
        { stat = "versatility", rating = 123, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/demonology/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "warlock", spec = "demonology",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 998, order = 2 },
        { stat = "haste", rating = 799, order = 3 },
        { stat = "mastery", rating = 397, order = 4 },
        { stat = "versatility", rating = 141, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/demonology/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "warlock", spec = "demonology",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 1092, order = 2 },
        { stat = "haste", rating = 809, order = 3 },
        { stat = "mastery", rating = 443, order = 4 },
        { stat = "versatility", rating = 99, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/destruction/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "warlock", spec = "destruction",
    primary = "intellect",
    secondary = {
        { stat = "haste", rating = 828, order = 2 },
        { stat = "crit", rating = 734, order = 3 },
        { stat = "mastery", rating = 494, order = 4 },
        { stat = "versatility", rating = 154, order = 5 },
    },
}

WoWLogsStatsPrio["warlock/destruction/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "warlock", spec = "destruction",
    primary = "intellect",
    secondary = {
        { stat = "crit", rating = 934, order = 2 },
        { stat = "haste", rating = 830, order = 3 },
        { stat = "mastery", rating = 565, order = 4 },
        { stat = "versatility", rating = 98, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/arms/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "warrior", spec = "arms",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 989, order = 2 },
        { stat = "haste", rating = 866, order = 3 },
        { stat = "mastery", rating = 357, order = 4 },
        { stat = "versatility", rating = 126, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/arms/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "warrior", spec = "arms",
    primary = "strength",
    secondary = {
        { stat = "crit", rating = 1033, order = 2 },
        { stat = "haste", rating = 936, order = 3 },
        { stat = "mastery", rating = 380, order = 4 },
        { stat = "versatility", rating = 75, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/fury/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "warrior", spec = "fury",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 973, order = 2 },
        { stat = "mastery", rating = 939, order = 3 },
        { stat = "crit", rating = 458, order = 4 },
        { stat = "versatility", rating = 141, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/fury/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "warrior", spec = "fury",
    primary = "strength",
    secondary = {
        { stat = "mastery", rating = 1040, order = 2 },
        { stat = "haste", rating = 1018, order = 3 },
        { stat = "crit", rating = 465, order = 4 },
        { stat = "versatility", rating = 94, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/protection/m+"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "m+", class = "warrior", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 981, order = 2 },
        { stat = "crit", rating = 579, order = 3 },
        { stat = "mastery", rating = 375, order = 4 },
        { stat = "versatility", rating = 246, order = 5 },
    },
}

WoWLogsStatsPrio["warrior/protection/raid"] = {
    updated = "2026-05-01T18:52:26Z",
    activity = "raid", class = "warrior", spec = "protection",
    primary = "strength",
    secondary = {
        { stat = "haste", rating = 1098, order = 2 },
        { stat = "crit", rating = 637, order = 3 },
        { stat = "mastery", rating = 391, order = 4 },
        { stat = "versatility", rating = 232, order = 5 },
    },
}

WoWLogsStatsPrio["death-knight/blood/m+"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 79.9 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/blood/raid"].heroes = {
        { hero = "san'layn", rank = 1, usage_pct = 0 },
        { hero = "deathbringer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/frost/m+"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 97.8 },
        { hero = "rider-of-the-apocalypse", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/frost/raid"].heroes = {
        { hero = "deathbringer", rank = 1, usage_pct = 99.6 },
        { hero = "rider-of-the-apocalypse", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/unholy/m+"].heroes = {
        { hero = "rider-of-the-apocalypse", rank = 1, usage_pct = 94.7 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["death-knight/unholy/raid"].heroes = {
        { hero = "rider-of-the-apocalypse", rank = 1, usage_pct = 97.5 },
        { hero = "san'layn", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/havoc/m+"].heroes = {
        { hero = "fel-scarred", rank = 1, usage_pct = 0 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/havoc/raid"].heroes = {
        { hero = "fel-scarred", rank = 1, usage_pct = 0 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/vengeance/m+"].heroes = {
        { hero = "annihilator", rank = 1, usage_pct = 98.7 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["demon-hunter/vengeance/raid"].heroes = {
        { hero = "annihilator", rank = 1, usage_pct = 99.7 },
        { hero = "aldrachi-reaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/balance/m+"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/balance/raid"].heroes = {
        { hero = "keeper-of-the-grove", rank = 1, usage_pct = 93.3 },
        { hero = "elune's-chosen", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/feral/m+"].heroes = {
        { hero = "druid-of-the-claw", rank = 1, usage_pct = 93 },
        { hero = "wildstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/feral/raid"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 97.7 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/guardian/m+"].heroes = {
        { hero = "elune's-chosen", rank = 1, usage_pct = 0 },
        { hero = "druid-of-the-claw", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/guardian/raid"].heroes = {
        { hero = "druid-of-the-claw", rank = 1, usage_pct = 98.1 },
        { hero = "elune's-chosen", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/restoration/m+"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 83.1 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["druid/restoration/raid"].heroes = {
        { hero = "wildstalker", rank = 1, usage_pct = 89.6 },
        { hero = "keeper-of-the-grove", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/augmentation/m+"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 99.1 },
        { hero = "chronowarden", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/augmentation/raid"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 59.5 },
        { hero = "chronowarden", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/devastation/m+"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 79.1 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/devastation/raid"].heroes = {
        { hero = "scalecommander", rank = 1, usage_pct = 94.3 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/preservation/m+"].heroes = {
        { hero = "chronowarden", rank = 1, usage_pct = 93 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["evoker/preservation/raid"].heroes = {
        { hero = "chronowarden", rank = 1, usage_pct = 98 },
        { hero = "flameshaper", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/beast-mastery/m+"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 51.5 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/beast-mastery/raid"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 97 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/marksmanship/m+"].heroes = {
        { hero = "sentinel", rank = 1, usage_pct = 69.7 },
        { hero = "dark-ranger", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/marksmanship/raid"].heroes = {
        { hero = "dark-ranger", rank = 1, usage_pct = 52.1 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/survival/m+"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 96.5 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["hunter/survival/raid"].heroes = {
        { hero = "pack-leader", rank = 1, usage_pct = 99.8 },
        { hero = "sentinel", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/arcane/m+"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 99.4 },
        { hero = "sunfury", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/arcane/raid"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 99.8 },
        { hero = "sunfury", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/fire/m+"].heroes = {
        { hero = "sunfury", rank = 1, usage_pct = 95.8 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/fire/raid"].heroes = {
        { hero = "sunfury", rank = 1, usage_pct = 98.1 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/frost/m+"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 99.3 },
        { hero = "frostfire", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["mage/frost/raid"].heroes = {
        { hero = "spellslinger", rank = 1, usage_pct = 100 },
}

WoWLogsStatsPrio["monk/brewmaster/m+"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/brewmaster/raid"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/mistweaver/m+"].heroes = {
        { hero = "conduit-of-the-celestials", rank = 1, usage_pct = 95.3 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/mistweaver/raid"].heroes = {
        { hero = "conduit-of-the-celestials", rank = 1, usage_pct = 95.1 },
        { hero = "master-of-harmony", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/windwalker/m+"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "conduit-of-the-celestials", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["monk/windwalker/raid"].heroes = {
        { hero = "shado-pan", rank = 1, usage_pct = 0 },
        { hero = "conduit-of-the-celestials", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/holy/m+"].heroes = {
        { hero = "herald-of-the-sun", rank = 1, usage_pct = 72.1 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/holy/raid"].heroes = {
        { hero = "herald-of-the-sun", rank = 1, usage_pct = 99.7 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/protection/m+"].heroes = {
        { hero = "lightsmith", rank = 1, usage_pct = 79.7 },
        { hero = "templar", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/protection/raid"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 90.3 },
        { hero = "lightsmith", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/retribution/m+"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 99.6 },
        { hero = "herald-of-the-sun", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["paladin/retribution/raid"].heroes = {
        { hero = "templar", rank = 1, usage_pct = 99.9 },
        { hero = "herald-of-the-sun", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/discipline/m+"].heroes = {
        { hero = "oracle", rank = 1, usage_pct = 97.3 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/discipline/raid"].heroes = {
        { hero = "oracle", rank = 1, usage_pct = 99.9 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/holy/m+"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 86.8 },
        { hero = "oracle", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/holy/raid"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 99 },
        { hero = "oracle", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/shadow/m+"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 69.8 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["priest/shadow/raid"].heroes = {
        { hero = "archon", rank = 1, usage_pct = 94.4 },
        { hero = "voidweaver", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/assassination/m+"].heroes = {
        { hero = "fatebound", rank = 1, usage_pct = 98.1 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/assassination/raid"].heroes = {
        { hero = "fatebound", rank = 1, usage_pct = 99.9 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/outlaw/m+"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 72.1 },
        { hero = "fatebound", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/outlaw/raid"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 97.9 },
        { hero = "fatebound", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/subtlety/m+"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 99.6 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["rogue/subtlety/raid"].heroes = {
        { hero = "trickster", rank = 1, usage_pct = 99.9 },
        { hero = "deathstalker", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/elemental/m+"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 98.2 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/elemental/raid"].heroes = {
        { hero = "stormbringer", rank = 1, usage_pct = 96.3 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/enhancement/m+"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 82.8 },
        { hero = "stormbringer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/enhancement/raid"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 97.2 },
        { hero = "stormbringer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/restoration/m+"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 74.2 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["shaman/restoration/raid"].heroes = {
        { hero = "totemic", rank = 1, usage_pct = 99.3 },
        { hero = "farseer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/affliction/m+"].heroes = {
        { hero = "soul-harvester", rank = 1, usage_pct = 96.4 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/affliction/raid"].heroes = {
        { hero = "soul-harvester", rank = 1, usage_pct = 99.2 },
        { hero = "hellcaller", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/demonology/m+"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 98.7 },
        { hero = "soul-harvester", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/demonology/raid"].heroes = {
        { hero = "diabolist", rank = 1, usage_pct = 85 },
        { hero = "soul-harvester", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/destruction/m+"].heroes = {
        { hero = "hellcaller", rank = 1, usage_pct = 58.4 },
        { hero = "diabolist", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warlock/destruction/raid"].heroes = {
        { hero = "hellcaller", rank = 1, usage_pct = 80 },
        { hero = "diabolist", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/arms/m+"].heroes = {
        { hero = "colossus", rank = 1, usage_pct = 72.5 },
        { hero = "slayer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/arms/raid"].heroes = {
        { hero = "slayer", rank = 1, usage_pct = 65.6 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/fury/m+"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 92.8 },
        { hero = "slayer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/fury/raid"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 94.2 },
        { hero = "slayer", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/protection/m+"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 96.9 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}

WoWLogsStatsPrio["warrior/protection/raid"].heroes = {
        { hero = "mountain-thane", rank = 1, usage_pct = 96.5 },
        { hero = "colossus", rank = 2, usage_pct = 0 },
}

